#!/bin/bash

source "$(dirname $0)/swman.lib.sh"

showUsage() {
  cat << EOF
Usage:
$0 [-u] ... update and upgrade all packages
$0 [-i <package-name-list>] ... install packages
$0 [-r <package-name-list>] ... remove packages
EOF
}

while getopts "uir" option; do
  case $option in
  u) packageUpdate;     exit 0 ;;
  i) operation=install;        ;;
  r) operation=remove;         ;;
  ?) showUsage;         exit 1 ;;
  esac
done
shift $(( OPTIND - 1 ))
success=1
for packageName in $*; do
  packageQuery $packageName
  if [ $? != 0 ]; then
    if [ $operation = install ]; then
      packageInstall $packageName
      if [ $? != 0 ]; then
        exit 1
      fi
    fi
  else
    if [ $operation = remove ]; then
      packageUninstall $packageName
      if [ $? != 0 ]; then
        exit 1
      fi
    fi
  fi
  success=0
done
if [ $success != 0 ]; then
  showUsage
  exit 1
fi
exit 0
