#!/bin/bash

# Sets the variable ID_LIKE containing the most generic
# distribution name.
# Example: ID_LIKE=arch, or ID_LIKE=debian
detectLinuxDistribution() {
  eval `cat /etc/*-release | grep ID_LIKE`
}

# DO NOT CHANGE! This is needed to detect the distribution name.
detectLinuxDistribution

# Query if a package is already installed.
packageQuery() {
  local packageName=$1
  if [ $ID_LIKE = arch ]; then
    pacman -Qi $packageName > /dev/null
    return $?
  fi
  if [ $ID_LIKE = debian ]; then
    dpkg-query -l $packageName > /dev/null
    return $?
  fi
  return 0
}

packageInstall() {
  local packageName=$1
  if [ $ID_LIKE = arch ]; then
    pacman --noconfirm -S $packageName
  fi
  if [ $ID_LIKE = debian ]; then
    apt-get --yes --force-yes -q=2 install $packageName
  fi
}

packageUninstall() {
  local packageName=$1
  if [ $ID_LIKE = arch ]; then
    pacman --noconfirm -R $packageName
  fi
  if [ $ID_LIKE = debian ]; then
    apt-get --yes --force-yes -q=2 --purge autoremove $packageName
  fi
}

package=lynx
#mosquitto

packageQuery $package
if [ $? != 0 ]; then
  packageInstall $package
fi
exit 0
